import time

# Data Sets
authorized_ip = {23,48,56,89,12,45,56,78,22,57,88,126}
Waiting = {54,98,32,65,87,23,78,56,98,123,456,126,324} 

# 1. Perform Logic Calculations First (Safe & Clean)
intruders = Waiting.difference(authorized_ip)
verified = authorized_ip.intersection(Waiting)
inactive = authorized_ip.difference(Waiting)
analyze = authorized_ip.union(Waiting)

# 2. Determine Security Status Dynamically
if len(intruders) > 0:
    status = "COMPROMISED"
    alert_header = "[!] CRITICAL ALERT: UNAUTHORIZED ACCESS DETECTED!"
    alert_action = "    - Action Required: Block these IPs immediately."
    show_alert = True
else:
    status = "SECURE"
    alert_header = "[✓] SYSTEM SECURE: No unauthorized access detected."
    alert_action = ""
    show_alert = False

# 3. Print Professional Report
print("=" * 40)
print("      CYBER SECURITY AUDIT REPORT      ")
print("=" * 40)
print(f"Generated by: Rohan Sanjay Jadhav")
print(f"Date: {time.strftime('%Y-%m-%d %H:%M:%S')}")
print("=" * 40)

# Section: Intruders
print(f"\n{alert_header}")
print(f"    - Total Intrusion Attempts: {len(intruders)}")
if show_alert:
    intruder_list = ", ".join(map(str, intruders))
    print(f"    - Suspicious IPs: {intruder_list}")
    print(alert_action)
else:
    print("    - No threats detected.")

# Section: Verified Users
print("\n[✓] AUTHORIZED ACCESS VERIFIED")
print(f"    - Valid Connections Found: {len(verified)}")
if len(verified) > 0:
    verified_list = ", ".join(map(str, verified))
    print(f"    - Verified IPs: {verified_list}")
else:
    print("    - No active authorized connections found.")

# Section: Inactive Accounts
print("\n[!] INACTIVE AUTHORIZED ACCOUNTS DETECTED")
print(f"    - Accounts with No Activity: {len(inactive)}")
if len(inactive) > 0:
    inactive_list = ", ".join(map(str, inactive))
    print(f"    - Inactive IPs: {inactive_list}")
    print("    - Action: Review accounts for potential compromise.")
else:
    print("    - All authorized accounts are active.")

# Section: Summary
print("\n" + "=" * 40)
print("SUMMARY")
print("=" * 40)
print(f"Total Unique IPs Analyzed: {len(analyze)}")
print(f"Security Status: {status}")
if status == "COMPROMISED":
    print("Recommendation: Initiate emergency protocol immediately.")
else:
    print("Recommendation: Continue standard monitoring.")
print("=" * 40)